# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EnergyStorageLocationEvaluator
                                 A QGIS plugin
 A tool to evaluate potential locations for energy storage facilities, providing options for static and mobile configurations based on various spatial criteria.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-01
        copyright            : (C) 2025 by Cristian Melendez
        email                : cristian.melendez@upr.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Cristian Melendez'
__date__ = '2025-01-01'
__copyright__ = '(C) 2025 by Cristian Melendez'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EnergyStorageLocationEvaluator class from file EnergyStorageLocationEvaluator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .energy_storage_location_evaluator import EnergyStorageLocationEvaluatorPlugin
    return EnergyStorageLocationEvaluatorPlugin()
